version: "3.9"
services:
  # server
  server:
    build:
      context: $PWD
      dockerfile: $PWD/Dockerfile
    links:
      - redis
    depends_on:
      - redis
    env_file:
      - .env
    command: ['./go-mservice-bench', '-x', 'server']
  # worker(s) - PLEASE test scaling by using: docker-compose up --scale worker=2
  worker:
    build:
      context: $PWD
      dockerfile: $PWD/Dockerfile
    links:
      - redis
    depends_on:
      - master
      - redis
    env_file:
      - .env
    command: ['./go-mservice-bench', '-x', 'worker']
  redis:
    image: redis:6.2.5
    ports:
      - '6379:6379'
    expose:
      - '6379'