version: "3.9"
services:
  # app:
  #   volumes:
  #     - $PWD:/usr/app
  #   build:
  #     context: $PWD
  #     dockerfile: $PWD/.docker/dev/Dockerfile
  #   links:
  #     - redis
  #   depends_on:
  #     - redis
  #   env_file:
  #     - .env
  redis:
    image: redis:6.2.5
    ports:
      - '6379:6379'
    expose:
      - '6379'